### ISSUE TITLE
forking for another wedding :)

### ISSUE THREAD

**Issue by 100ideas** [InsidersByte/honeymoon-gift-list#211]
Hi! @InsidersByte I'm getting married later this summer and I wanted to thank you for publicly sharing your repo. I'd like to use it as the basis for our wedding website, with your permission - and take the opportunity to finally play around with express.

Please let me know if you have any concerns or open issues you'd like help with.

Thanks!
Mac n Lisa

**Comment by InsidersByte** [comment]
Hi @100ideas 

I am getting married this summer as well!

No worries, I am glad someone else is using it! Maybe we can merge some of your changes back in once you are done? 

I am running this in production already, so it is stable (as far as I aware). The issues that are open are mainly low priority, but if you want to work on any of them then that is great! You will probably come up with some more as you use it.

I realise that I haven't updated the README with instructions on how to get this running so I will try to do that shortly.

**Comment by 100ideas** [comment]
Awesome! 👍 💒 🎉 

I got it running earlier tonight and it looks great. I am mostly going to make some cosmetic changes and use the handy frontend you've created for adding the particulars of our content.

After that, maybe work out a way for users to nominate songs for our spotify playlist.

My only significant js development experience previously has been some fairly simple meteor apps, so I am excited to have such a well-formed express/react/es2015 project to learn from.

**Comment by InsidersByte** [comment]
awesome!

yeah that is a feature I wanted to add, at the moment I have just setup a email address where I take suggestions.

happy learning! If you have any questions give me a shout 👍
