### ISSUE TITLE
Deploy & hosting example

### ISSUE THREAD

**Issue by 100ideas** [InsidersByte/honeymoon-gift-list#216]
I have gotten my fork running on the free tier of redhat openshift, after a fair amount of hair-pulling.

I'm more interested in running it with [dokku](http://dokku.viewdocs.io/dokku) (a diy-mini-heroku) on a VM like digitalocean.

I've tried naively deploying the entire app to heroku and dokku instances, but in both cases the build process fails for me - the default buildpack sets `NODE_ENV=production` before `npm install` runs, so devDependencies like `rimraf` in the package.json file are not installed and cause commands like `npm run clean` to fail.

So I suspect your deploy process involves building everything locally and only deploying the `dist/`directory to production. I'm curious how you have the deploy scripts set up.

Thanks!

**Comment by 100ideas** [comment]
So in my case I think I was overlooking that `NODE_ENV` and `NPM_CONFIG_PRODUCTION` have different effects, and I wanted the latter but was messing with the former - thanks, [dokku #1434](https://github.com/dokku/dokku/issues/1434#issuecomment-161160045).

More generally, I'm curious about deploy strategies with javascript-only apps - running webpack on my dinky VPS seems like a waste of time when I already run it locally. Do you have a separate repo you use to deploy the `dist/' directory, or do you ship up everything to your server and have it rebuild there?

**Comment by InsidersByte** [comment]
at the moment, I am deploying to [heroku](https://www.heroku.com/) and setting `NPM_CONFIG_PRODUCTION=false` and rebuilding it there. I then use [mLab](https://mlab.com/) to host the mongo database.

It deploys to automatically heroku when:
1. something is pushed to master
2. when the ci build completes successfully

**Comment by InsidersByte** [comment]
if i am honest i haven't looked too much into deployment strategies as i normally deploy to heroku so rebuilding isn't too bad, it takes a bit of time, but i only need to do it every now and again

**Comment by InsidersByte** [comment]
Congratulations on getting it running btw 😄

**Comment by 100ideas** [comment]
Thanks for sharing. Yeah I'm pleased to have figured out dokku and digitalocean. I like heroku but I am annoyed by their price-point, esp since mongo etc often costs extra. With dokku, I get close to the convenience of heroku + deeper access to the build stack + much more affordable hosting.

Perhaps you'd be interested in exploring dokku as well. It's pretty slick, [digitalocean can spin up an image with it preinstalled in like 60 seconds](https://www.digitalocean.com/features/one-click-apps/dokku/). Steps to duplicate heroku functionality:
1. sign up for digitalocean. setup ssh keys. spin up [dokku "droplet"](https://www.digitalocean.com/features/one-click-apps/dokku/).
2. note the IP. visit w/ web browser to set up dokku box.
3. set up [domain name with digitalocean](https://cloud.digitalocean.com/networking#actions-domains) for dokku droplet (could be some little [subdomain](http://dokku.viewdocs.io/dokku/dns/#using-a-sub-domain-myappmyserverexampletld), like apps.insidersbytes.com)
4. if you want to try deploying the our-wedding-heros app, adjust the `database:`[ environment variable](https://github.com/100ideas/our-wedding-heroes/blob/develop/server/config/config.js#L4) in `server/config/config.js` to set from `process.env.MONGO_URL`
5. `> git remote add dokku dokku@<your-dokku-box>:<app-name>` (dokku uses <app-name> as the subdomain from which it serves the app, i.e. `our-wedding-heros.apps.insiderbytes.com`)
6. `> git push dokku <your fav branch>:master` (dokku only deploys from it's master branch). You'll see familiar, heroku-like feedback after pushing.
7. Set up [mongo dokku plugin](https://github.com/dokku/dokku-mongo): `ssh root@<your-dokku-box>` (uses ssh keys set up previously) 
   1. `> dokku config:set <app-name> NPM_CONFIG_PRODUCTION=false`
   2. `> dokku plugin:install https://github.com/dokku/dokku-mongo.git mongo`
   3. `> dokku mongo:create <app-db-name>`
   4. `> dokku mongo:link <app-db-name> <app-name>`
8. Potentially push to dokku again from your development box, wait for build. Should automatically hook into mongo and init db, then get served by nginx at `<app-name>.<dokku-sub-domain>.<domain>.<TLD>` 👍 
- If you like dokku, there is a [bash script](http://dokku.viewdocs.io/dokku/community/clients/#bash-zsh-etc-dokku_clientsh) that helps with administration.
- if npm build fails on your droplet, maybe you should add [some swap space](https://codentrick.com/check-swap-file-to-prevent-npm-install-can-be-killed/) or upgrade droplet size.
- [Deploying the Right Way: Dokku on Digital Ocean](https://www.andrewmunsell.com/blog/dokku-tutorial-digital-ocean/) goes into more detail about all the steps above.
- maybe set up [`forever` or `upstart` to keep node running](http://stackoverflow.com/a/26798229/957984) in dokku - )not sure if it's necessary)
- lastly, If you decide to try out digitalocean, you can use my [promo code](https://m.do.co/c/ae32ed44c587) to get $10 in hosting credit, enough for a month or two of hosting - I'll get $25 in credit too.

**Comment by InsidersByte** [comment]
[mLab](https://mlab.com/) give you a free 500mb mongo instance 😄 and i am using the free tier (i'm cheap like that 😉). If you have to pay for Heroku it is expensive, but it's so easy!

Thanks for the information! I will have a look at it, I haven't heard of dokku before. When I do I will use your promo code 👍

**Comment by 100ideas** [comment]
Well I guess the $5/mo 512mb ram "droplet" on digitalocean is _slightly_ cheaper than the $7 512mb hobby dyno on heroku, but obviously heroku is far more convenient. Hm.

On the other hand, for $10/mo, you can use a single dokku image on a digitalocean 1gb droplet to deploy 5-10 apps almost as easily as heroku once it's set up.

I probably should have just gone with heroku instead of figuring this all out though.

**Comment by 100ideas** [comment]
btw, I have been filling my dev db with most of our content, I am using the following to update the production db. here it is in case it's useful to you.

``` bash
# map mongodb to external ports
# note first port listed and use below as <port>. these ports map from nginx to
# the typical mongo ports running in the mongo docker container.
$ dokku mongo:expose <dbname>

# get mongodb auth
$ dokku mongo:info <app-name>
> mongodb://<username>:<password>@<internal-docker-hostname>:27017/<dbname> 

# drop remote db and replace with dev db
$ mongodump --archive --db <dbname> | mongorestore --host <dokku-hostname> --port <port> --username <username> --password <password> --drop --archive --db <dbname>
```

**Comment by InsidersByte** [comment]
I am just using the free tier, I have been using it since I started the project last year. The sleeping thing is a little annoying.

I was thinking of looking at some point at different ways to deploy / update releases and I was also considering using docker. 

It's always good to learn new things 😄.

Thanks I was actually looking at pulling my production database down to my local to check a few things!
